/*
 * generated by Xtext
 */
package com.ge.research.osate.verdict.dsl.ui;

import com.ge.research.osate.verdict.dsl.ui.contentassist.VerdictTemplateProposalProvider;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.contentassist.ITemplateProposalProvider;

/** Use this class to register components to be used within the IDE. */
public class VerdictUiModule extends AbstractVerdictUiModule {
    public static final String INJECTOR_NAME = "com.ge.research.osate.verdict.dsl.Verdict";

    public VerdictUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }

    @Override
    public Class<? extends ITemplateProposalProvider> bindITemplateProposalProvider() {
        return VerdictTemplateProposalProvider.class;
    }
}
