/* Copyright (c) 2019-2020, Board of Trustees of the University of Iowa.
   All rights reserved.

   Use of this source code is governed by a BSD 3-Clause License that
   can be found in the LICENSE file.

   @author: M. Fareed Arif
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.08.04 at 09:31:01 PM CDT
//

@jakarta.xml.bind.annotation.XmlSchema(
        namespace = "http://www.example.org/BlameAssignment",
        elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.uiowa.clc.verdict.blm;
