/*
 * generated by Xtext
 */
package com.ge.research.osate.verdict.dsl.scoping;

import org.osate.xtext.aadl2.properties.scoping.PropertiesScopeProvider;

/**
 * This class contains custom scoping description.
 *
 * <p>See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping on how and
 * when to use it.
 */
public class VerdictScopeProvider extends PropertiesScopeProvider {
    // This isn't working for some reason
    // AGREE got it to work...
    // But we can just use validation instead
}
