(* Example from
   http://www.ewp.rpi.edu/hartford/~ernesto/S2008/SMRE/Papers/Andrews-FTA-tutor.pdf
   slides 36-37 *)  

#use "top.ml";;

let lFromErr err = log(1. /. (1. -. err)) ;;

let ea = Leaf("A", (lFromErr 0.1), 1.);;
let eb = Leaf("B", (lFromErr 0.1), 1.);;
let ec = Leaf("C", (lFromErr 0.1), 1.);;
let ed = Leaf("D", (lFromErr 0.1), 1.);;
let g2 = PRO [eb; ec];;
let g3 = PRO [eb; ed];;
let g1 = SUM [g2; g3];;
let top = SUM [g1; ea];;

cutsets top;;
probErrorCut top;;

(* From the paper:

   We evaluated OSATE on a number of examples and found errors. Using the example
   on page 36 of [1], event B is a repeated event in the fault tree. OSATE, assigns
   different event labels to the instances of event B, which leads to the wrong
   results with OpenFTA. The latest version of OpenFTA, version 2, was released in
   1991 and even after fixing the erroneous fault tree generated by OSATE, OpenFTA
   reports a probability for the top-level event of 0.1108, which is inconsistent
   with the actual result, 0.1171, reported in [1] and by our tool. 

*)
