/*
 * generated by Xtext
 */
package com.ge.research.osate.verdict.dsl.ui.labeling;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
public class VerdictDescriptionLabelProvider extends org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider {
    // Not currently used
}
