/*
 * generated by Xtext
 */
package com.ge.research.osate.verdict.dsl.ui.quickfix;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class VerdictQuickfixProvider extends org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider {
    // Not currently used
}
