/*
 * generated by Xtext
 */
package com.ge.research.osate.verdict.dsl;

/** Initialization support for running Xtext languages without equinox extension registry */
public class VerdictStandaloneSetup extends VerdictStandaloneSetupGenerated {

    public static void doSetup() {
        new VerdictStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
