/*
 * generated by Xtext
 */
package com.ge.research.osate.verdict.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
public class VerdictOutlineTreeProvider extends DefaultOutlineTreeProvider {
	// Not currently used
}
