# Runs whenever a pull request is created, modified, or reopened

name: VERDICT Integration Workflow

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

# Builds VERDICT source with Java and Maven
# Caches Maven dependencies

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        distribution: [ temurin ]
        java-version: [ 17 ]
        os: [ ubuntu-22.04 ]

    steps:
    - name: Check out VERDICT source
      uses: actions/checkout@v3.5.2

    - name: Set up GraphViz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Set up Java and Maven
      uses: actions/setup-java@v3.11.0
      with:
        cache: maven
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java-version }}

    - name: Build VERDICT source
      run: |
        mvn -B install -f tools/verdict-back-ends/verdict-bundle/z3-native-libs/pom.xml
        mvn -B package -f tools/pom.xml -Dtycho.localArtifacts=ignore
      env:
        GraphVizPath: /usr/bin
