name: VERDICT Integration Workflow

# Runs whenever a pull request is created, reopened, or has a change
# made to it

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

# Runs a build job as a CI check:
# - Builds VERDICT source & runs unit tests

jobs:
  build:
    strategy:
      matrix:
        distribution: [ temurin ]
        java-version: [ 11 ]
        os: [ ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out VERDICT source
      uses: actions/checkout@v2.3.5

    - name: Set up GraphViz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Set up Java
      uses: actions/setup-java@v2.3.1
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java-version }}
        cache: maven

    - name: Build VERDICT source
      run: |
        mvn -B install --file tools/verdict-back-ends/verdict-bundle/z3-native-libs/pom.xml
        mvn -B package -Dtycho.localArtifacts=ignore --file tools/pom.xml
      env:
        GraphVizPath: /usr/bin
